---
title: "Final_Assignment"
author: "Brecht Van Buggenhout"
date: "12/14/2022"
output: html_document
---

Data cleaning -- same for every model

```{r}
# clear the environment
rm(list = ls())

# read in csv file and aprropriate libraries
library(Hmisc)
dat_train <- read.table("train.csv", sep=",", header=TRUE)
dat_test <- read.csv("test.csv")
gender <- read.csv("gender_submission.csv")
dim(dat_train)
describe(dat_train)[,1:12]
describe(dat_test)[,1:11]
head(dat_train)
dat_test <- merge(dat_test,gender, by = "PassengerId")

# get rid of columns that are not useful to predictions
# name, passengerid, ticket, and cabin
dat_train_fin <- dat_train[,-c(1,4,9,11)]
dat_test_fin <- dat_test[,-c(1,3,8,10)]

# get rid of null values
df1_train <- na.omit(dat_train_fin)
describe(df1_train)
describe(dat_test_fin)

# convert sex to binary values
df1_train$Sex <- ifelse(df1_train$Sex=="male",1,0)
dat_test_fin$Sex <- ifelse(dat_test_fin$Sex=="male",1,0)
dat_test_fin$Age <- ifelse(is.na(dat_test_fin$Age) == TRUE, 30.27, dat_test_fin$Age)
dat_test_fin$Fare <- ifelse(is.na(dat_test_fin$Fare) == TRUE, 35.63, dat_test_fin$Fare)

# removing rows without any embarked port
df1_train <- df1_train[!df1_train$Embarked == "",]

# converting embarked to factor
df1_train$Embarked <- as.factor(df1_train$Embarked)
```

Data exploration

```{r}
# how many people died versus how many people survived
table(df1_train$Survived)
library(ggplot2)
```

```{r}
# histogram to show distribution of age
ggplot(df1_train, aes(x = Age)) +
  geom_histogram(breaks = seq(0,80, by = 5)) 
labs(x = "Age") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r}
# histogram of fare --> using log
ggplot(df1_train, aes(x = log(Fare))) +
  geom_histogram(breaks = seq(0,10, by = 1)) 
labs(x = "Fare") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r}
library(dplyr)
df1_train %>%
  group_by(Embarked) %>%
  summarise(
    zeros = sum(Survived == 0),
    ones = sum(Survived == 1),
    n = n(),
    proportion = mean(Survived)
  )
```

Neural nets --> neural net 1 performed the best

```{r}
# clear the environment
rm(list = ls())
```

```{r}
# read in csv file and aprropriate libraries
library(Hmisc)
dat_train <- read.table("train.csv", sep=",", header=TRUE)
dat_test <- read.csv("test.csv")
gender <- read.csv("gender_submission.csv")
dim(dat_train)
describe(dat_train)[,1:12]
describe(dat_test)[,1:11]
head(dat_train)
dat_test <- merge(dat_test,gender, by = "PassengerId")
```

```{r}
# get rid of columns that are not useful to predictions
# name, passengerid, ticket, and cabin
dat_train_fin <- dat_train[,-c(1,4,9,11)]
dat_test_fin <- dat_test[,-c(1,3,8,10)]

# get rid of null values
df1_train <- na.omit(dat_train_fin)
describe(df1_train)
describe(dat_test_fin)
```

```{r}
# convert sex to binary values
df1_train$Sex <- ifelse(df1_train$Sex=="male",1,0)
dat_test_fin$Sex <- ifelse(dat_test_fin$Sex=="male",1,0)
dat_test_fin$Age <- ifelse(is.na(dat_test_fin$Age) == TRUE, 30.27, dat_test_fin$Age)
dat_test_fin$Fare <- ifelse(is.na(dat_test_fin$Fare) == TRUE, 35.63, dat_test_fin$Fare)
# removing rows without any embarked port
df1_train <- df1_train[!df1_train$Embarked == "",]
# converting embarked to factor
df1_train$Embarked <- as.factor(df1_train$Embarked)
```

```{r}
# create formula
form1 <- formula(df1_train$Survived~.)

# We commence with a good combination from prior studies
# maximal iterations of 100, and a decay= of 0.0001.
library(nnet)
set.seed(1)
n1 <- nnet(form1, data=df1_train, size=3, maxit=500, decay=0.001)

# lets check predictions
yhat.n1 <- predict(n1, dat_test_fin)

#create confusion matrix
table(yhat.n1[,1]>0.5, dat_test_fin$Survived)

# check the ROC curve and AUC
library("pROC")
n1.roc <- roc(dat_test_fin$Survived, yhat.n1[,1], direction="<")
n1.roc
plot(n1.roc, lwd=3)
```

```{r}
# create dataset to show results of first predictions
round(yhat.n1)
df <- data.frame(round(yhat.n1))
names(df) <- c('Survived')
df$PassengerId <- c(892:1309)
write.csv(df, "Survived.csv", row.names=FALSE)
```

```{r}
# neural net 2
set.seed(4)
n2 <- nnet(form1, data=df1_train, size=10, maxit=200, decay=0.001)
yhat.n2 <- predict(n2, dat_test_fin)
table(yhat.n2[,1]>0.5, dat_test_fin$Survived)
n2.roc <- roc(dat_test_fin$Survived, yhat.n2[,1], direction="<")
n2.roc
plot(n2.roc, add = TRUE, col="blue")
```

```{r}
# create dataset fro 2nd neural net
round(yhat.n2)
df2 <- data.frame(round(yhat.n2))
names(df2) <- c('Survived')
df2$PassengerId <- c(892:1309)
write.csv(df2, "Survived2.csv", row.names=FALSE)
```

```{r}
# neural net 3
set.seed(4)
n3 <- nnet(form1, data=df1_train, size=10, maxit=500, decay=0.001)
yhat.n3 <- predict(n3, dat_test_fin)
table(yhat.n3[,1]>0.5, dat_test_fin$Survived)
n3.roc <- roc(dat_test_fin$Survived, yhat.n3[,1], direction="<")
n3.roc
plot(n3.roc, add = TRUE, col="red")
```

```{r}
# create dataset fro 3rd neural net
round(yhat.n3)
df3 <- data.frame(round(yhat.n3))
names(df3) <- c('Survived')
df3$PassengerId <- c(892:1309)
write.csv(df3, "Survived3.csv", row.names=FALSE)
```

```{r}
# lets use more iterations for neural net 4
set.seed(4)
n4 <- nnet(form1, data=df1_train, size=5, maxit=1000, decay=0.0001)
yhat.n4 <- predict(n4, dat_test_fin)
table(yhat.n4[,1]>0.5, dat_test_fin$Survived)
n4.roc <- roc(dat_test_fin$Survived, yhat.n4[,1], direction="<")
n4.roc
plot(n4.roc, add = TRUE, col="green")
```

```{r}
# create dataset fro 4th neural net
round(yhat.n4)
df4 <- data.frame(round(yhat.n4))
names(df4) <- c('Survived')
df4$PassengerId <- c(892:1309)
write.csv(df4, "Survived4.csv", row.names=FALSE)
```

```{r}
# compare nets
library(corrplot)
temp <- data.frame(yhat.n1[,1],yhat.n2[,1],yhat.n3[,1],yhat.n4[,1],dat_test_fin$Survived)
rho <- cor(temp)
corrplot(rho, method="number")
```

Classification tree --> did better than 2 worst neural nets, but worse than best 2 neural nets
```{r}
# clear the environment
rm(list = ls())

# read in csv file and aprropriate libraries
library(Hmisc)
dat_train <- read.table("train.csv", sep=",", header=TRUE)
dat_test <- read.csv("test.csv")
gender <- read.csv("gender_submission.csv")
dim(dat_train)
describe(dat_train)[,1:12]
describe(dat_test)[,1:11]
head(dat_train)
dat_test <- merge(dat_test,gender, by = "PassengerId")
```

```{r}
# get rid of columns that are not useful to predictions
# name, passengerid, ticket, and cabin
dat_train_fin <- dat_train[,-c(1,4,9,11)]
dat_test_fin <- dat_test[,-c(1,3,8,10)]

# get rid of null values
df1_train <- na.omit(dat_train_fin)
describe(df1_train)
```

```{r}
# convert sex to binary values
df1_train$Sex <- ifelse(df1_train$Sex=="male",1,0)
dat_test_fin$Sex <- ifelse(dat_test_fin$Sex=="male",1,0)
dat_test_fin$Age <- ifelse(is.na(dat_test_fin$Age) == TRUE, 30.27, dat_test_fin$Age)
dat_test_fin$Fare <- ifelse(is.na(dat_test_fin$Fare) == TRUE, 35.63, dat_test_fin$Fare)
# removing rows without any embarked port
df1_train <- df1_train[!df1_train$Embarked == "",]
# converting embarked to factor
df1_train$Embarked <- as.factor(df1_train$Embarked)
```

```{r}
# create classification tree
library(corrplot)
library(pROC)
library(ROCR)
library(rpart)
form1 <- formula(Survived~.)
t1 <- rpart(form1, data=df1_train, cp=.001, method="class")
plot(t1,uniform=T,compress=T,margin=.05,branch=0.3)
text(t1, cex=.7, col="navy",use.n=TRUE)
```

```{r}
# plotting the t1
plotcp(t1)

# 
CP <- printcp(t1)

# the left variable is a good choice for pruning if below the line in classification trees
cp <- CP[,1][CP[,2]==2]
cp

# prune according to cp calculate above
t2 <- prune(t1,cp=cp[1])
plot(t2,uniform=T,compress=T,margin=.05,branch=0.3)
text(t2, cex=.7, col="navy",use.n=TRUE)
```

```{r}
# make predictions based on tree 2
yhat.t2 <- predict(t2, dat_test_fin, type="prob")[,2]
table(yhat.t2>0.5,dat_test_fin$Survived)
```

```{r}
# plotting the ROC curve and calculating the AUC
t2.roc <- roc(dat_test_fin$Survived, yhat.t2, direction="<")
t2.roc
plot(t2.roc, lwd=3)
```

```{r}
# create dataset to show results of first predictions
round(yhat.t2)
df <- data.frame(round(yhat.t2))
names(df) <- c('Survived')
df$PassengerId <- c(892:1309)
write.csv(df, "Survived_classtree.csv", row.names=FALSE)
df
```

Random Forest --> did better than class tree but worse than best neural nets
```{r}
# clear the environment
rm(list = ls())

# read in csv file and aprropriate libraries
library(Hmisc)
library(pROC)
library(ROCR)
library(rpart)
dat_train <- read.table("train.csv", sep=",", header=TRUE)
dat_test <- read.csv("test.csv")
gender <- read.csv("gender_submission.csv")
dim(dat_train)
describe(dat_train)[,1:12]
describe(dat_test)[,1:11]
head(dat_train)
dat_test <- merge(dat_test,gender, by = "PassengerId")
```

```{r}
# get rid of columns that are not useful to predictions
# name, passengerid, ticket, and cabin
dat_train_fin <- dat_train[,-c(1,4,9,11)]
dat_test_fin <- dat_test[,-c(1,3,8,10)]

# get rid of null values
df1_train <- na.omit(dat_train_fin)
describe(df1_train)
describe(dat_test_fin)
```

```{r}
# convert sex to binary values
df1_train$Sex <- ifelse(df1_train$Sex=="male",1,0)
dat_test_fin$Sex <- ifelse(dat_test_fin$Sex=="male",1,0)
a <- 30.27
dtest <- dat_test_fin[,-c(7)]
dtest$Age <- ifelse(is.na(dtest$Age) == TRUE, a, dtest$Age)
dtest$Fare <- ifelse(is.na(dtest$Fare) == TRUE, 35.63, dtest$Fare)
describe(dtest)
# removing rows without any embarked port
df1_train <- df1_train[!df1_train$Embarked == "",]
# converting embarked to factor
df1_train$Embarked <- as.factor(df1_train$Embarked)
library(dplyr)
```

```{r}
# Setting up the random forest
library(xgboost)
library(randomForest)
X <- as.matrix(df1_train[,-c(1,8)])
Y <- df1_train$Survived

mtry <- round(ncol(X)^0.5); mtry

# Fitting random forest to the dataset
ntree <- 1000
set.seed(652)
rf1 <- randomForest(x=X, y=Y, ntree=ntree, mtry=mtry, importance=TRUE)
rf1
```

```{r}
# summary of the random forest
summary(rf1)
names(rf1)
```

```{r}
# look at "importance' since it gives us the influence of each feature
importance(rf1)
# look at the rf1 in a plot setting
varImpPlot(rf1)
```

```{r}
# evaluating predictions
pred.rf1 <- predict(rf1, dtest)
table(pred.rf1, dtest$Survived)
yhat.rf1 <- predict(rf1, dtest)
yhat.rf1
```

```{r}
# let's look at the ROC curve and AUC
library(pROC)
rf1.roc <- roc(dtest$Survived, yhat.rf1, direction="<")
rf1.roc
plot(rf1.roc, lwd=3)
```

```{r}
# create dataset to show results of first predictions
round(yhat.rf1)
df <- data.frame(round(yhat.rf1))
names(df) <- c('Survived')
df$PassengerId <- c(892:1309)
write.csv(df, "Survived_rndmforest.csv", row.names=FALSE)
df
```

GLM --> slightly worse than class tree - worst in total
```{r}
# clear the environment
rm(list = ls())

# read in csv file and aprropriate libraries
library(dplyr)
library(Hmisc)
library(pROC)
library(ROCR)
library(rpart)
library(MASS)
library(mvtnorm)
library(ggplot2)
library(class)
dat_train <- read.table("train.csv", sep=",", header=TRUE)
dat_test <- read.csv("test.csv")
gender <- read.csv("gender_submission.csv")
dim(dat_train)
describe(dat_train)[,1:12]
describe(dat_test)[,1:11]
head(dat_train)
dat_test <- merge(dat_test,gender, by = "PassengerId")
```

```{r}
# get rid of columns that are not useful to predictions
# name, passengerid, ticket, and cabin
dat_train_fin <- dat_train[,-c(1,4,9,11)]
dat_test_fin <- dat_test[,-c(1,3,8,10)]

# get rid of null values
df1_train <- na.omit(dat_train_fin)
describe(df1_train)
describe(dat_test_fin)
```

```{r}
# remove 0 value for fare in train data
df1_train <- df1_train[df1_train$Fare > 0,] #7 observations removed

# convert sex to binary values
df1_train$Sex <- ifelse(df1_train$Sex=="male",1,0)
dat_test_fin$Sex <- ifelse(dat_test_fin$Sex=="male",1,0)
dat_test_fin$Age <- ifelse(is.na(dat_test_fin$Age) == TRUE, 30.27, dat_test_fin$Age)
dat_test_fin$Fare <- ifelse(is.na(dat_test_fin$Fare) == TRUE, 35.63, dat_test_fin$Fare)
df1_train$Fare <- log(df1_train$Fare)
dat_test_fin$Fare <- log(dat_test_fin$Fare)
# removing rows without any embarked port
df1_train <- df1_train[!df1_train$Embarked == "",]
# converting embarked to factor
df1_train$Embarked <- as.factor(df1_train$Embarked)
# remove embarked
df1_train <- df1_train[,-c(8)]
```

```{r}
# run glm
glm <- glm(Survived ~., family = "binomial", data = df1_train)
summary(glm)
```

```{r}
# predictions of this glm
yhat1 <- predict(glm, dat_test_fin, type = "response")
test.glm <- rep(0,length(dat_test_fin[,1]))
test.glm[yhat1 > 0.5] <- 1
table(test.glm, dat_test_fin$Survived)
```

```{r}
# AUC and ROC
g1.roc <- roc(dat_test_fin$Survived, yhat1, direction="<")
g1.roc
plot(g1.roc, lwd=3)
```

```{r}
# create dataset to show results of first predictions
round(yhat1)
df <- data.frame(round(yhat1))
names(df) <- c('Survived')
df$PassengerId <- c(892:1309)
write.csv(df, "Survived_glm.csv", row.names=FALSE)
df
```
